version: '3'

services:
  app:
    image: haroldcris/php7.4
    container_name: app
    restart: unless-stopped
    volumes:
      - ./server/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./app:/var/www
    networks:
      - mynetwork


  webserver:
    image: nginx
    container_name: mynginx
    restart: always
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./server/nginx/conf.d:/etc/nginx/conf.d/
      - ./app:/var/www
    networks:
      - mynetwork

  adminer:
    image: adminer
    container_name: myadminer
    restart: always
    ports: 
      - 9000:8080
    networks:
      - mynetwork
  
  db:
    image: mariadb
    container_name: mymariadb
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mariadb
      TZ: Asia/Manila
    volumes:
      - ./server/mysql/my.cnf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql
    networks:
      - mynetwork
  

networks:
  mynetwork:
    driver: bridge
